### ISSUE TITLE
Mobile - Missing Clickable areas

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/featured_match#26]
The following areas are clickable with the betting site like on the desktop version.

<img width="353" alt="Screenshot 2021-10-12 at 09 10 18" src="https://user-images.githubusercontent.com/37311649/136917751-7e4ab7ab-76a4-440c-81ea-78e6eb7931b1.png">

**Comment by migbash** [comment]
Amended - reflected in the next `Pull-Request`
