### ISSUE TITLE
Value bet height and sizes not respecting the design

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/featured_match#8]
<img width="564" alt="Screenshot 2021-10-06 at 09 20 17" src="https://user-images.githubusercontent.com/37311649/136166441-d1c1e026-0540-4504-afca-1a03655014d7.png">

![Screenshot 2021-10-06 at 09 20 26](https://user-images.githubusercontent.com/37311649/136166470-ca2dccbc-4e89-482b-8a66-095c3c6dbd35.png)

**Comment by jonsnowpt** [comment]
Still not correct.

<img width="546" alt="Screenshot 2021-10-10 at 10 25 47" src="https://user-images.githubusercontent.com/37311649/136690148-4f1d1ede-4a82-4f01-baba-f1f8f53ecd34.png">

**Comment by migbash** [comment]
Amended - reflected in the next `Pull-Request`
